name: Test GH Pages Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm ci
          npm run build
        env:
          REACT_APP_SKDEV: ${{ secrets.REACT_APP_SKDEV }}
          REACT_APP_SKPROD: ${{ secrets.REACT_APP_SKPROD }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: build
